### ISSUE TITLE
Does not work on OS X

### ISSUE THREAD

**Issue by mikz** [kingluo/luajit.io#6]
Looks like because of posix realtime extensions it does not work on OSX.

See https://gist.github.com/jbenet/1087739 for workarounds.

It fails with: 

```
luajit: lib/ljio/core/timer.lua:5: dlopen(librt.dylib, 5): image not found
stack traceback:
    [C]: in function 'load'
    lib/ljio/core/timer.lua:5: in main chunk
```

**Comment by kingluo** [comment]
Thanks for reminding.
In fact, the luajit.io only supports Linux, because it depends on a lot of linux specific features, e.g. epoll, as well as linux-specific libc.

**Comment by creationix** [comment]
I would recommend making it clear on your homepage that you only work on linux.  This will help set expectations.  Trust me, it's never good when people think your project can do more than it really can.

That said, I think this is a really good idea.  I went with using libuv for my project (luvit.io) because cross-platform is a big deal to me, but I also love the minimal simplicity of this project.

**Comment by kingluo** [comment]
Thanks for your advice.
I would improve the homepage later.
